# Generated by Django 4.2.7 on 2023-11-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=20),
        ),
    ]
